### PR TITLE
Fixes postgresql lowercased column labels

### LINKED ISSUE #4: error retrieving tableInfo while using postgresql
Hello [this](https://github.com/bilak/database-metadata-postgresql-issue) is my sample application.   With [this](https://github.com/bilak/database-metadata-postgresql-issue/blob/master/src/test/java/com/github/bilak/DatabaseMetadataPostgresqlIssueApplicationTests.java) unit test you can run the application. It will download embedded postgresql, create the orders table. `getTables` method will try to get table informations about orders table. However this is not working on postgresql. Please can you look into this and tell me if it has something to do with `database-metadata-bind` or I should contact the postgre dev team?

Many thanks.

### PR DESCRIPTION
**Pull request by bilak**
fixes #4

### CODE REVIEW

**Comment by bilak** [comment]
or maybe wait for [this](https://github.com/pgjdbc/pgjdbc/issues/830)

**Comment by onacit** [comment]
This fix, actually, seems to be a smart move.

**Comment by bilak** [comment]
would you mind to provide new release with this fix? I'm using for now my custom `Utils` class as a workaround, but I'd like to take away all workarounds. Thanks

**Comment by jinahya** [comment]
Let me serve you as you wished.

**Comment by onacit** [comment]
`1.0.4` released to the central.

**Comment by bilak** [comment]
thank you!

**Pull request merged**
